<?php
/**
 * SmartCart — Mock Payment Confirmation Page
 *
 * This file ONLY exists in mock/dev mode.  It simulates the hosted payment
 * page that a real provider (PayMe, Meshulam) would show after the user is
 * redirected to their site.
 *
 * URL: /api/payments/mock_confirm.php?payment_id=X&sig=HMAC
 *
 * On confirmation → calls the webhook handler internally to update DB,
 * then redirects to PAYMENT_SUCCESS_URL.
 *
 * On cancel → redirects back to the group page.
 *
 * PHP 7.4 compatible.
 */

require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/db.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../services/PaymentService.php';

$payment_id = (int)($_GET['payment_id'] ?? 0);
$sig        = trim($_GET['sig'] ?? '');

if (!$payment_id || !$sig) {
    http_response_code(400);
    exit('Invalid payment link.');
}

// Verify HMAC signature generated by PaymentService::createMockLink()
$secret   = defined('PAYMENT_WEBHOOK_SECRET') ? PAYMENT_WEBHOOK_SECRET : 'dev_secret_change_me';
$expected = hash_hmac('sha256', (string)$payment_id, $secret);

if (!hash_equals($expected, $sig)) {
    http_response_code(403);
    exit('Invalid or expired payment link.');
}

// Load payment details
$pdo  = getPDO();
$stmt = $pdo->prepare("
    SELECT pay.id, pay.status, pay.amount_ils, pay.currency,
           pay.group_id, pay.provider_transaction_id,
           p.name AS product_name
    FROM   payments pay
    LEFT JOIN products p ON p.id = pay.product_id
    WHERE  pay.id = ?
");
$stmt->execute([$payment_id]);
$pay = $stmt->fetch();

if (!$pay) {
    http_response_code(404);
    exit('Payment not found.');
}

// If already in a terminal state, redirect immediately
if (in_array($pay['status'], ['paid', 'completed'], true)) {
    $redirect = defined('PAYMENT_SUCCESS_URL')
        ? PAYMENT_SUCCESS_URL . '?payment_id=' . $payment_id
        : APP_URL . '/pages/my-orders.php';
    header('Location: ' . $redirect);
    exit;
}

$group_url = APP_URL . '/pages/group.php?id=' . $pay['group_id'];

// ── Handle POST actions ────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['mock_action'] ?? '';

    if ($action === 'pay' || $action === 'fail') {
        $new_status = $action === 'pay' ? 'paid' : 'failed';

        // Call the webhook handler via an internal HTTP POST so all the
        // DB logic stays in one place.  Fall back to direct DB call if
        // curl / allow_url_fopen is disabled on the server.
        $webhook_url = APP_URL . '/api/payments/webhook.php';
        $secret      = defined('PAYMENT_WEBHOOK_SECRET') ? PAYMENT_WEBHOOK_SECRET : '';
        $payload     = json_encode([
            'payment_id'     => $payment_id,
            'transaction_id' => $pay['provider_transaction_id'] ?? '',
            'status'         => $new_status,
        ]);

        $sent = false;
        if (function_exists('curl_init')) {
            $ch = curl_init($webhook_url);
            curl_setopt_array($ch, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST           => true,
                CURLOPT_POSTFIELDS     => $payload,
                CURLOPT_HTTPHEADER     => [
                    'Content-Type: application/json',
                    'X-Webhook-Token: ' . $secret,
                ],
                CURLOPT_TIMEOUT        => 10,
            ]);
            $resp = curl_exec($ch);
            $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            $sent = ($code >= 200 && $code < 300);
        }

        if (!$sent) {
            // Direct DB path (same logic as webhook handler)
            require_once __DIR__ . '/../../includes/notifications.php';
            process_payment_directly($pdo, $payment_id, $new_status);
        }

        if ($new_status === 'paid') {
            $redirect = defined('PAYMENT_SUCCESS_URL')
                ? PAYMENT_SUCCESS_URL . '?payment_id=' . $payment_id
                : APP_URL . '/pages/my-orders.php';
        } else {
            $redirect = $group_url . '&payment_failed=1';
        }

        header('Location: ' . $redirect);
        exit;
    }

    if ($action === 'cancel') {
        header('Location: ' . $group_url . '&cancelled=1');
        exit;
    }
}

// ── Render mock payment page ──────────────────────────────────────────────
$amount_fmt = '₪' . number_format((float)$pay['amount_ils'], 2);
$product    = htmlspecialchars($pay['product_name'] ?? 'SmartCart Purchase');
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mock Payment — SmartCart</title>
<style>
  *, *::before, *::after { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: #f0f4ff;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0;
    padding: 20px;
  }
  .card {
    background: white;
    border-radius: 16px;
    padding: 36px 32px;
    max-width: 440px;
    width: 100%;
    box-shadow: 0 8px 32px rgba(0,0,0,.10);
    text-align: center;
  }
  .mock-badge {
    display: inline-block;
    background: #fef3c7;
    color: #92400e;
    border: 1px solid #fde68a;
    border-radius: 999px;
    padding: 4px 12px;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: .3px;
    margin-bottom: 20px;
  }
  h1 { font-size: 22px; font-weight: 800; color: #111827; margin: 0 0 6px; }
  .product { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
  .amount {
    font-size: 40px;
    font-weight: 900;
    color: #7c3aed;
    margin-bottom: 8px;
    letter-spacing: -1px;
  }
  .currency-note { font-size: 12px; color: #9ca3af; margin-bottom: 28px; }
  .fake-card {
    background: #f9fafb;
    border: 1px solid #e5e7eb;
    border-radius: 10px;
    padding: 16px;
    margin-bottom: 24px;
    text-align: left;
  }
  .fake-card label { display: block; font-size: 11px; color: #6b7280; margin-bottom: 4px; }
  .fake-card .field {
    background: white;
    border: 1px solid #d1d5db;
    border-radius: 6px;
    padding: 9px 12px;
    font-size: 14px;
    color: #374151;
    margin-bottom: 12px;
    width: 100%;
  }
  .fake-row { display: flex; gap: 10px; }
  .fake-row .field-wrap { flex: 1; }
  .btn { display: block; width: 100%; padding: 14px; border: none; border-radius: 10px;
         font-size: 16px; font-weight: 700; cursor: pointer; transition: opacity .15s; }
  .btn-pay   { background: #7c3aed; color: white; margin-bottom: 10px; }
  .btn-pay:hover { opacity: .9; }
  .btn-fail  { background: #fee2e2; color: #dc2626; font-size: 13px; padding: 10px; }
  .btn-fail:hover { background: #fecaca; }
  .btn-cancel { background: transparent; color: #6b7280; font-size: 13px; padding: 8px; margin-top: 6px; text-decoration: underline; border: none; cursor: pointer; }
  .dev-note { font-size: 11px; color: #9ca3af; margin-top: 18px; line-height: 1.5; }
</style>
</head>
<body>
<div class="card">
  <div class="mock-badge">⚙️ Mock Payment — Dev Mode Only</div>
  <h1>Complete Payment</h1>
  <p class="product"><?= $product ?> · Group #<?= (int)$pay['group_id'] ?></p>
  <div class="amount"><?= $amount_fmt ?></div>
  <p class="currency-note">Israeli Shekel (ILS) · Simulated charge</p>

  <!-- Fake card UI (not collected — mock only) -->
  <div class="fake-card">
    <label>Card number</label>
    <input class="field" value="4242 4242 4242 4242" readonly>
    <div class="fake-row">
      <div class="field-wrap"><label>Expiry</label><input class="field" value="12/28" readonly></div>
      <div class="field-wrap"><label>CVV</label><input class="field" value="123" readonly></div>
    </div>
    <label>Card holder</label>
    <input class="field" value="Test User" readonly>
  </div>

  <form method="POST">
    <button class="btn btn-pay" name="mock_action" value="pay">
      ✓ Confirm Payment — <?= $amount_fmt ?>
    </button>
    <button class="btn btn-fail" name="mock_action" value="fail">
      ✗ Simulate Payment Failure
    </button>
    <button class="btn-cancel" name="mock_action" value="cancel" type="submit">
      Cancel and go back
    </button>
  </form>

  <p class="dev-note">
    This page simulates a real payment provider's hosted checkout.<br>
    Set <code>PAYMENT_PROVIDER=payme</code> (or <code>meshulam</code>) in <code>.env</code>
    to use a live provider.
  </p>
</div>
</body>
</html>
<?php

/**
 * Direct DB fallback used when curl cannot make an internal HTTP call
 * (e.g. server blocks loopback requests).  Mirrors webhook.php logic.
 */
function process_payment_directly(PDO $pdo, int $payment_id, string $new_status): void
{
    $pdo->beginTransaction();
    try {
        $stmt = $pdo->prepare("SELECT * FROM payments WHERE id = ? FOR UPDATE");
        $stmt->execute([$payment_id]);
        $pay  = $stmt->fetch();
        if (!$pay) { $pdo->rollBack(); return; }

        if (in_array($pay['status'], ['paid', 'completed', 'failed'], true)) {
            $pdo->rollBack(); return;
        }

        if ($new_status === 'paid') {
            $pdo->prepare("UPDATE payments SET status='paid', paid_at=NOW() WHERE id=?")
                ->execute([$payment_id]);

            $product_id = (int)($pay['product_id'] ?? 0);
            if (!$product_id) {
                $ps = $pdo->prepare("SELECT product_id FROM group_purchases WHERE id=?");
                $ps->execute([$pay['group_id']]);
                $product_id = (int)($ps->fetchColumn() ?: 0);
            }

            $pdo->prepare("UPDATE group_members SET status='paid' WHERE group_id=? AND user_id=?")
                ->execute([$pay['group_id'], $pay['user_id']]);

            if ($product_id) {
                $pdo->prepare("INSERT IGNORE INTO orders (group_id, payment_id, user_id, product_id, amount_paid, shipping_status) VALUES (?,?,?,?,?,'pending')")
                    ->execute([$pay['group_id'], $payment_id, $pay['user_id'], $product_id, $pay['amount_ils']]);
            }
            $pdo->commit();

            // Check all-paid
            $s = $pdo->prepare("SELECT COUNT(*) AS t, SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS p FROM group_members WHERE group_id=?");
            $s->execute([$pay['group_id']]);
            $r = $s->fetch();
            if ($r && (int)$r['t'] > 0 && (int)$r['p'] >= (int)$r['t']) {
                $pdo->prepare("UPDATE group_purchases SET status='order_ready' WHERE id=? AND status='ready_for_payment'")
                    ->execute([$pay['group_id']]);
            }
        } else {
            $pdo->prepare("UPDATE payments SET status='failed' WHERE id=?")->execute([$payment_id]);
            $pdo->commit();
        }
    } catch (\Throwable $e) {
        if ($pdo->inTransaction()) $pdo->rollBack();
        PaymentService::log('mock_direct_error', ['error' => $e->getMessage()]);
    }
}
